[package]
name = "seraph"
version = "0.1.0"
authors = ["Mason Kramer <mason.kramer@gmail.com>"]

[dependencies]
left-pad = "1.0.0"
regex = "0.2.0"
clippy = { version = "*", optional = true }
vec_map = "*"
itertools = "0.7.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_error"] }
flexi_logger = "*"
petgraph = "*"
rand = "*"
indoc = "*"
lazy_static = "*"

[dependencies.gosgf]
path = "gosgf"

[profile.release]
lto = true

[profile.bench]
lto = true

[profile.dev]
opt-level = 2
codegen-units = 4
