[package]
name = "golden"
version = "0.1.0"
authors = ["Mason Kramer <mason.kramer@gmail.com>"]

[dependencies.lazy_static]
version = "0.1.1"

[dependencies]
left-pad = "1.0.0"
regex = "0.2.0"
clippy = { version = "*", optional = true }
vec_map = "*"
itertools = "0.7.3"

[dependencies.gosgf]
path = "gosgf"

[profile.release]
lto = true

[profile.bench]
lto = true

[profile.dev]
opt-level = 1
codegen-units = 4
